### ISSUE TITLE
您好，在训练时出现这个问题。An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

### ISSUE THREAD

**Issue by liziUCAS** [bojone/seq2seq#12]
An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

**Comment by bojone** [comment]
完全没改动模型部分？

**Comment by Jiramew** [comment]
我也出现了这个问题，请问有什么解决办法吗？

**Comment by bojone** [comment]
用最新版试试？近期更新了代码。

**Comment by Jiramew** [comment]
@bojone 解决了，感谢~
