### ISSUE TITLE
python36跑不通

### ISSUE THREAD

**Issue by darrenwang00** [bojone/seq2seq#9]

**Comment by bojone** [comment]
两个选项：
1、改用python2.7；
2、自己想办法。

**Comment by bzqweiyi** [comment]
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/apple/Desktop/Algorithm/Keras/seq2seq/couplet_by_seq_tagging.py", line 63, in <module>
    train_dict[j][1].append(y_train[i])
TypeError: 'map' object is not subscriptable

**Comment by bzqweiyi** [comment]
> _No description provided._
the same to you. how can you solve the problem?

**Comment by bzqweiyi** [comment]
> 两个选项：
> 1、改用python2.7；
> 2、自己想办法。
you should supply the new way for us.

**Comment by LiJianGuo2333** [comment]
`x_train = map(string2id, x_train_txt)`改成`x_train = list(map(string2id, x_train_txt))`就行了，y_train, x_test, y_test也是一样
